// Generated by CoffeeScript 1.9.1
(function() {
  var A, B, C, aleat, faireQCM, liste, ordre, qA, qB, rB, rC, sol1, sol2, trad, type;

  type = Math.floor(Math.random() * 6);

  aleat = [0, 0, 0];

  ordre = [[0, 1, 1, 2], [0, 1, 2, 1], [0, 1, 1, 2], [0, 1, 2, 1], [1, 0, 2, 1], [0, 1, 2, 1]];

  qA = ["Tout", "Tout", "Quelque", "Quelque", "Aucun", "Quelque"];

  rB = ["est", "est", "est", "est", "n'est", "n'est pas"];

  qB = ["tout", "aucun", "tout", "aucun", "tout", "tout"];

  rC = ["est", "n'est", "est", "n'est", "est", "est"];

  A = ["suspect", "policier", "juge", "avocat", "chauffeur", "majordome", "détective", "greffier"];

  B = ["noir", "arabe", "étranger", "bavard", "fumeur", "muet", "gangster", "politicien"];

  C = ["gentil", "coupable", "malin", "imbécile", "innocent", "méchant", "escroc", "prisonnier"];

  liste = [A, B, C];

  sol1 = ["Tout", "Aucun", "Quelque", "Quelque", "aucun", "Quelque"];

  sol2 = ["est", "n'est", "est", "n'est pas", "n'est", "n'est pas"];

  trad = ["non-", ""];

  faireQCM = function() {
    var i, option;
    aleat = [Math.floor(Math.random() * 8), Math.floor(Math.random() * 8), Math.floor(Math.random() * 8)];
    $("#probleme1").text(qA[type] + " " + liste[ordre[type][0]][aleat[ordre[type][0]]] + " " + rB[type] + " " + liste[ordre[type][1]][aleat[ordre[type][1]]]);
    $("#probleme2").text(qB[type] + " " + liste[ordre[type][2]][aleat[ordre[type][2]]] + " " + rC[type] + " " + liste[ordre[type][3]][aleat[ordre[type][3]]]);
    $(".sA").text(" " + A[aleat[0]]);
    $(".sB").text(" " + B[aleat[1]]);
    $(".sC").text(" " + C[aleat[2]]);
    for (option = i = 0; i <= 3; option = ++i) {
      $("#o" + option).text(sol1[option] + " " + A[aleat[0]] + " " + sol2[option] + " " + C[aleat[2]]);
    }
    return true;
  };

  $(function() {
    faireQCM();
    $('.jeton').draggable({
      snap: false
    });
    $('#proposition').selectmenu({
      change: function(event, data) {
        var choix;
        choix = parseInt(data.item.value.split('solution')[1]);
        if (choix === 4) {
          return alert("Si, si, ce syllogisme a une solution !");
        } else {
          if (type === choix || (type === 4 && choix === 1) || (type === 5 && choix === 3)) {
            return alert("Bravo, la conclusion est effectivement que : \n " + sol1[choix] + " " + A[aleat[0]] + " " + sol2[choix] + " " + C[aleat[2]]);
          } else {
            return alert("Non, la conclusion du syllogisme n'est pas que :\n " + sol1[choix] + " " + A[aleat[0]] + " " + sol2[choix] + " " + C[aleat[2]]);
          }
        }
      }
    });
    return $('.cellule').droppable({
      accept: ".jeton",
      tolerance: "intersect",
      drop: function(event, ui) {
        var debut, diagnostic, fin, milieu, textsortie;
        diagnostic = $(this).attr("id").split("prem")[1];
        diagnostic = diagnostic.split("conc");
        debut = parseInt(diagnostic[0]);
        diagnostic = diagnostic[1].split("mid");
        milieu = parseInt(diagnostic[1]);
        fin = parseInt(diagnostic[0]);
        if (ui.draggable.hasClass('gris')) {
          if (debut > 1 || fin > 1) {
            textsortie = "N'auriez-vous pas plutôt dû utiliser un jeton rouge ?";
          } else {
            if (milieu === 1) {
              textsortie = "Vous venez de coder le fait qu'aucun " + trad[debut] + A[aleat[0]] + " " + trad[fin] + C[aleat[2]] + " n'est " + B[aleat[1]];
            } else {
              textsortie = "Vous venez de coder le fait que tout " + trad[debut] + A[aleat[0]] + " " + trad[fin] + C[aleat[2]] + "s est " + B[aleat[1]];
            }
          }
        } else {
          if (debut <= 1 && fin <= 1) {
            textsortie = "N'auriez-vous pas plutôt dû utiliser un jeton gris ?";
          } else {
            if (debut > 1) {
              textsortie = "Vous venez de coder le fait que quelque " + trad[fin] + C[aleat[2]] + " n'est pas " + B[aleat[1]];
            } else {
              textsortie = "Vous venez de coder le fait que quelque " + trad[debut] + A[aleat[0]] + " n'est pas " + B[aleat[1]];
            }
          }
        }
        $('#sortie').text(textsortie);
        return true;
      }
    });
  });

}).call(this);
