// Generated by CoffeeScript 1.9.1
(function() {
  var A, B, C, faireQCM, ref, ref1, resoudreSyll, s1, s2, s3, s4, trad, type;

  type = Math.floor(Math.random() * 6);

  ref = ["machin", "truc", "chose"], A = ref[0], B = ref[1], C = ref[2];

  trad = ["non-", ""];

  ref1 = ["Tout", "est", "Tout", "est"], s1 = ref1[0], s2 = ref1[1], s3 = ref1[2], s4 = ref1[3];

  faireQCM = function() {
    $(".sA").text(" " + A + " ");
    $(".sB").text(" " + B + " ");
    $(".sC").text(" " + C + " ");
    $(".sxB").text(" " + B + " ");
    $(".sxC").text(" " + C + " ");
    return resoudreSyll();
  };

  resoudreSyll = function() {
    var solution;
    solution = "On ne peut pas conclure";
    if (s1 === "Tout") {
      if (s2 === "est") {
        if (s3 === "Tout") {
          if (s4 === "est") {
            $(".sxB").text(" " + B + " ");
            $(".sxC").text(" " + C + " ");
            solution = "Tout " + A + " est " + C;
          } else {
            solution = "Le deuxième verbe n'est pas bon";
          }
        } else {
          if (s3 === "Aucun" && s4 === "n'est") {
            $(".sxB").text(" " + C + " ");
            $(".sxC").text(" " + B + " ");
            solution = "Aucun " + A + "s n'est " + C;
          }
        }
      } else {
        solution = "Le premier verbe n'est pas bon";
      }
    }
    if (s1 === "Quelque") {
      if (s2 === "est") {
        if (s3 === "Tout") {
          if (s4 === "est") {
            $(".sxB").text(" " + B + " ");
            $(".sxC").text(" " + C + " ");
            solution = "Quelque " + A + " est " + C;
          } else {
            solution = "Le deuxième verbe n'est pas bon";
          }
        } else {
          if (s3 === "Aucun" && s4 === "n'est") {
            $(".sxB").text(" " + C + " ");
            $(".sxC").text(" " + B + " ");
            solution = "Quelque " + C + " n'est pas " + A;
          }
        }
      } else {
        solution = "Le premier verbe n'est pas bon";
      }
    }
    if (s3 === "Tout") {
      if (s4 === "est") {
        if (s1 === "Aucun") {
          if (s2 === "n'est") {
            $(".sxB").text(" " + C + " ");
            $(".sxC").text(" " + B + " ");
            solution = "Aucun " + A + " n'est " + C;
          } else {
            solution = "Le premier verbe n'est pas bon";
          }
        } else {
          if (s1 === "Quelque" && s2 === "n'est pas") {
            $(".sxB").text(" " + C + " ");
            $(".sxC").text(" " + B + " ");
            solution = "Quelque " + A + " n'est pas " + C;
          }
        }
      } else {
        solution = "Le deuxième verbe n'est pas bon";
      }
    }
    solution += ".";
    return $("#sorsyl").text(solution);
  };

  $(function() {
    faireQCM();
    $('.jeton').draggable({
      snap: false
    });
    $("#eA").on("change", function() {
      A = $("#eA").val();
      return faireQCM();
    });
    $("#eB").on("change", function() {
      B = $("#eB").val();
      return faireQCM();
    });
    $("#eC").on("change", function() {
      C = $("#eC").val();
      return faireQCM();
    });
    $('.cellule').droppable({
      accept: ".jeton",
      tolerance: "intersect",
      drop: function(event, ui) {
        var debut, diagnostic, fin, milieu, textsortie;
        diagnostic = $(this).attr("id").split("prem")[1];
        diagnostic = diagnostic.split("conc");
        debut = parseInt(diagnostic[0]);
        diagnostic = diagnostic[1].split("mid");
        milieu = parseInt(diagnostic[1]);
        fin = parseInt(diagnostic[0]);
        if (ui.draggable.hasClass('gris')) {
          if (debut > 1 || fin > 1) {
            textsortie = "N'auriez-vous pas plutôt dû utiliser un jeton rouge ?";
          } else {
            if (milieu === 1) {
              textsortie = "Vous venez de coder le fait qu'aucun " + trad[debut] + A + " " + trad[fin] + C + " n'est " + B;
            } else {
              textsortie = "Vous venez de coder le fait que tous les " + trad[debut] + A + "s " + trad[fin] + C + "s sont " + B + "s";
            }
          }
        } else {
          if (debut <= 1 && fin <= 1) {
            textsortie = "N'auriez-vous pas plutôt dû utiliser un jeton gris ?";
          } else {
            if (debut > 1) {
              textsortie = "Vous venez de coder le fait que quelques " + trad[fin] + C + "s ne sont pas des " + B + "s";
            } else {
              textsortie = "Vous venez de coder le fait que quelques " + trad[debut] + A + "s ne sont pas des " + B + "s";
            }
          }
        }
        $('#sortie').text(textsortie);
        return true;
      }
    });
    $('#choixA').selectmenu({
      change: function(event, data) {
        s1 = data.item.value;
        return resoudreSyll();
      }
    });
    $('#verbe1').selectmenu({
      change: function(event, data) {
        s2 = data.item.value;
        return resoudreSyll();
      }
    });
    $('#choixB').selectmenu({
      change: function(event, data) {
        s3 = data.item.value;
        return resoudreSyll();
      }
    });
    return $('#verbe2').selectmenu({
      change: function(event, data) {
        s4 = data.item.value;
        return resoudreSyll();
      }
    });
  });

}).call(this);
