// Generated by CoffeeScript 1.9.1
(function() {
  var A, B, C, faireQCM, ref, trad, type;

  type = Math.floor(Math.random() * 6);

  ref = ["machin", "truc", "chose"], A = ref[0], B = ref[1], C = ref[2];

  trad = ["non-", ""];

  faireQCM = function() {
    $(".sA").text(" " + A + "s ");
    $(".sB").text(" " + B + "s ");
    return $(".sC").text(" " + C + "s ");
  };

  $(function() {
    faireQCM();
    $('.jeton').draggable({
      snap: false
    });
    $("#eA").on("change", function() {
      A = $("#eA").val();
      return faireQCM();
    });
    $("#eB").on("change", function() {
      B = $("#eB").val();
      return faireQCM();
    });
    $("#eC").on("change", function() {
      C = $("#eC").val();
      return faireQCM();
    });
    return $('.cellule').droppable({
      accept: ".jeton",
      tolerance: "intersect",
      drop: function(event, ui) {
        var debut, diagnostic, fin, milieu, textsortie;
        diagnostic = $(this).attr("id").split("prem")[1];
        diagnostic = diagnostic.split("conc");
        debut = parseInt(diagnostic[0]);
        diagnostic = diagnostic[1].split("mid");
        milieu = parseInt(diagnostic[1]);
        fin = parseInt(diagnostic[0]);
        if (ui.draggable.hasClass('gris')) {
          if (debut > 1 || fin > 1) {
            textsortie = "N'auriez-vous pas plutôt dû utiliser un jeton rouge ?";
          } else {
            if (milieu === 1) {
              textsortie = "Vous venez de coder le fait qu'aucun " + trad[debut] + A + " " + trad[fin] + C + " n'est " + B;
            } else {
              textsortie = "Vous venez de coder le fait que tous les " + trad[debut] + A + "s " + trad[fin] + C + "s sont " + B + "s";
            }
          }
        } else {
          if (debut <= 1 && fin <= 1) {
            textsortie = "N'auriez-vous pas plutôt dû utiliser un jeton gris ?";
          } else {
            if (debut > 1) {
              textsortie = "Vous venez de coder le fait que quelques " + trad[fin] + C + "s ne sont pas des " + B + "s";
            } else {
              textsortie = "Vous venez de coder le fait que quelques " + trad[debut] + A + "s ne sont pas des " + B + "s";
            }
          }
        }
        $('#sortie').text(textsortie);
        return true;
      }
    });
  });

}).call(this);
