// Generated by CoffeeScript 1.9.1
(function() {
  var A, B, C, aleat, faireQCM, liste, ordre, qA, qB, rB, rC, sol1, trad;

  aleat = [0, 0, 0];

  ordre = [[0, 1, 1, 2], [0, 1, 2, 1], [0, 1, 1, 2], [0, 1, 2, 1], [1, 0, 2, 1], [0, 1, 2, 1]];

  qA = ["Tout", "Tout", "Quelque", "Quelque", "Aucun", "Quelque"];

  rB = ["est", "est", "est", "est", "n'est", "n'est pas"];

  qB = ["tout", "aucun", "tout", "aucun", "tout", "tout"];

  rC = ["est", "n'est", "est", "n'est", "est", "est"];

  A = ["suspect", "policier", "juge", "avocat", "chauffeur", "majordome", "détective", "greffier"];

  B = ["noir", "arabe", "étranger", "bavard", "fumeur", "muet", "gangster", "politicien"];

  C = ["gentil", "coupable", "malin", "imbécile", "innocent", "méchant", "escroc", "prisonnier"];

  liste = [A, B, C];

  sol1 = ["Il n'y a pas de", "Il n'y a que des"];

  trad = ["non-", ""];

  faireQCM = function() {
    aleat = [Math.floor(Math.random() * 8), Math.floor(Math.random() * 8), Math.floor(Math.random() * 8)];
    $(".sA").text(" " + A[aleat[0]] + "s ");
    $(".sC").text(" " + B[aleat[1]] + "s ");
    return true;
  };

  $(function() {
    faireQCM();
    $('.jeton').draggable({
      snap: false
    });
    return $('.cellule').droppable({
      accept: ".jeton",
      tolerance: "intersect",
      drop: function(event, ui) {
        var debut, diagnostic, fin, milieu, textsortie;
        diagnostic = $(this).attr("id").split("prem")[1];
        diagnostic = diagnostic.split("conc");
        debut = parseInt(diagnostic[0]);
        diagnostic = diagnostic[1].split("mid");
        milieu = parseInt(diagnostic[1]);
        fin = parseInt(diagnostic[0]);
        if (ui.draggable.hasClass('gris')) {
          if (debut === 1) {
            if (milieu === 1) {
              textsortie = "Le dernier jeton code le fait qu'aucun " + A[aleat[0]] + " n'est " + B[aleat[1]];
            } else {
              textsortie = "Le dernier jeton code le fait que tout " + A[aleat[0]] + " est " + B[aleat[1]];
            }
          } else {
            if (milieu === 1) {
              textsortie = "Le dernier jeton code le fait que tout " + B[aleat[1]] + " est " + A[aleat[0]];
            } else {
              textsortie = "Le dernier jeton code le fait que tout le monde est " + A[aleat[0]] + " ou " + B[aleat[1]];
            }
          }
        } else {
          if (milieu === 1) {
            if (debut === 1) {
              textsortie = "Le dernier jeton code le fait qu'il existe un " + A[aleat[0]] + " " + B[aleat[1]];
            } else {
              textsortie = "Le dernier jeton code le fait qu'il existe un " + B[aleat[1]] + " qui n'est pas " + A[aleat[0]];
            }
          } else {
            if (debut === 1) {
              textsortie = "Le dernier jeton code le fait qu'il existe un " + A[aleat[0]] + " qui n'est pas " + B[aleat[1]];
            } else {
              textsortie = "Le dernier jeton code le fait qu'il existe quelqu'un qui n'est ni  " + B[aleat[1]] + ", ni " + A[aleat[0]];
            }
          }
        }
        $('#sortie').text(textsortie);
        return true;
      }
    });
  });

}).call(this);
