// Generated by CoffeeScript 1.9.1
(function() {
  var A, B, C, faireQCM, n;

  n = 0;

  A = ["suspect", "policier", "juge", "avocat", "chauffeur", "majordome"];

  B = ["noir", "arabe", "étranger", "bavard", "fumeur", "muet"];

  C = ["gentil", "coupable", "malin", "imbécile", "innocent", "méchant"];

  faireQCM = function() {
    var a, b, c;
    a = Math.floor(Math.random() * 6);
    $(".premisseA").text(A[a]);
    b = Math.floor(Math.random() * 6);
    $(".premisseB").text(B[b]);
    c = Math.floor(Math.random() * 6);
    $(".premisseC").text(C[c]);
    return true;
  };

  $(function() {
    faireQCM();
    $('.jeton').draggable()({
      snap: false
    });
    return $('.cellule').droppable({
      accept: ".jeton",
      tolerance: "intersect",
      drop: function(event, ui) {
        $('sortie').text($(this));
        return true;
      }
    });
  });

}).call(this);
