// Generated by CoffeeScript 1.9.1
(function() {
  var A, B, C, a, b, c, faireQCM, liste, ordre, qA, qB, rB, rC, ref, sol1, sol2, soln, type;

  type = 0;

  ref = [0, 0, 0], a = ref[0], b = ref[1], c = ref[2];

  ordre = [[a, b, b, c], [a, b, c, b], [a, b, b, c], [a, b, c, b], [b, a, c, b], [a, b, c, b]];

  qA = ["Tous les", "Tous les", "Quelques", "Quelques", "Aucun des", "Quelques"];

  rB = ["sont des", "sont des", "sont des", "sont des", "ne sont des", "ne sont pas des"];

  qB = ["tous les", "aucun des", "tous les", "aucun des", "tous les", "tous les"];

  rC = ["sont des", "ne sont des", "ne sont pas des", "ne sont des", "sont des", "tous les"];

  A = ["suspect", "policier", "juge", "avocat", "chauffeur", "majordome"];

  B = ["noir", "arabe", "étranger", "bavard", "fumeur", "muet"];

  C = ["gentil", "coupable", "malin", "imbécile", "innocent", "méchant"];

  liste = [A, B, C];

  soln = [[a, c], [a, c], [a, c], [a, c], [a, c], [a, c]];

  sol1 = ["Tous les", "Aucun des", "Quelques", "Quelques", "Aucun des", "Quelques"];

  sol2 = ["sont des", "ne sont des", "sont des", "ne sont pas des", "ne sont des", "ne sont pas des"];

  faireQCM = function() {
    var aleat;
    aleat = [Math.floor(Math.random() * 6), Math.floor(Math.random() * 6), Math.floor(Math.random() * 6)];
    $("#probleme1").text(qA[type] + " " + liste[ordre[type][0]][aleat[ordre[type][0]]] + "s " + rB[type] + " " + liste[ordre[type][1]][aleat[ordre[type][1]]] + "s");
    $("#probleme2").text(qB[type] + " " + liste[ordre[type][2]][aleat[ordre[type][2]]] + "s " + rC[type] + " " + liste[ordre[type][3]][aleat[ordre[type][3]]] + "s");
    return true;
  };

  $(function() {
    faireQCM();
    $('.jeton').draggable()({
      snap: false
    });
    return $('.cellule').droppable({
      accept: ".jeton",
      tolerance: "intersect",
      drop: function(event, ui) {
        alert("dropped !!!");
        $('sortie').text($(this));
        return true;
      }
    });
  });

}).call(this);
